/**
 * Inline the workflow prompts into the bundle.
 *
 * The .md files under layers/workflow/prompts/ are the source of truth. This
 * writes them into one generated TypeScript module so `dist/agent-wallet.mjs`
 * stays a single file with no sidecar prompt directory to lose on install.
 * `npm run prompts` regenerates it; a test fails when it drifts.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const promptsDir = fileURLToPath(new URL("../layers/workflow/prompts/", import.meta.url));
const outFile = fileURLToPath(new URL("../layers/workflow/src/prompts.generated.ts", import.meta.url));

export interface Manifest {
  purpose: Record<string, string>;
  modes: Record<string, string[]>;
  produces: Record<string, string>;
}

export function buildModule(): string {
  const manifest = JSON.parse(readFileSync(join(promptsDir, "manifest.json"), "utf8")) as Manifest;
  const parameters = JSON.parse(readFileSync(join(promptsDir, "parameters.json"), "utf8")) as Record<string, string>;

  const prompts: Record<string, string> = {};
  for (const file of readdirSync(promptsDir).sort()) {
    if (!file.endsWith(".md")) continue;
    prompts[file.replace(/\.md$/, "")] = readFileSync(join(promptsDir, file), "utf8");
  }

  const missing: string[] = [];
  for (const steps of Object.values(manifest.modes)) {
    for (const step of steps) if (!(step in prompts)) missing.push(step);
  }
  if (missing.length > 0) {
    throw new Error(`manifest names steps with no prompt file: ${[...new Set(missing)].join(", ")}`);
  }

  return [
    "// Generated by scripts/export-prompts.ts from layers/workflow/prompts/. Do not edit.",
    "// Run `npm run prompts` after changing any prompt.",
    "",
    "export interface WorkflowManifest {",
    "  purpose: Record<string, string>;",
    "  modes: Record<string, string[]>;",
    "  produces: Record<string, string>;",
    "}",
    "",
    `export const MANIFEST: WorkflowManifest = ${JSON.stringify(manifest, null, 2)};`,
    "",
    `export const PARAMETERS: Record<string, string> = ${JSON.stringify(parameters, null, 2)};`,
    "",
    `export const PROMPTS: Record<string, string> = ${JSON.stringify(prompts, null, 2)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(outFile, buildModule());
  console.log("layers/workflow/src/prompts.generated.ts");
}
